baseURL = "/"
title = "Ape Commerce"
disableKinds = ["taxonomy", "term"]

[module.hugoVersion]
extended = true
[[module.imports]]
path = "github.com/google/docsy"
[[module.imports]]
path = "github.com/google/docsy/dependencies"

[markup.goldmark.parser.attribute]
block = true
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
style = "pygments"

[imaging]
resampleFilter = "Lanczos"
anchor = "Center"
quality = 80

[outputs]
section = ["HTML", "RSS", "print"]

[services.googleAnalytics]
id = "UA-00000000-0"

[params]
copyright = "Ape Commerce"
offlineSearch = true
algolia_docsearch = false

[params.ui]
navbar_translucent_over_cover_disable = true
sidebar_menu_compact = true
footer_about_disable = true

[[params.links.developer]]
name = "GitHub"
icon = "fab fa-github"
url = "https://github.com/ApeCommerce"
