baseURL = "/"
title = "Ape Commerce"

# Content
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableMissingTranslationPlaceholders = true

# Code highlight
pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsUseClassic = false

# Robots
enableRobotsTXT = true

# Taxonomy
disableKinds = ["taxonomy", "term"]

[module.hugoVersion]
extended = true
[[module.imports]]
path = "github.com/google/docsy"
disable = false
[[module.imports]]
path = "github.com/google/docsy/dependencies"
disable = false

[languages.en]
languageName = "English"

[markup.goldmark.parser.attribute]
block = true
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
style = "dracula"

[imaging]
resampleFilter = "Lanczos"
anchor = "Center"
quality = 80

[services.googleAnalytics]
id = "UA-00000000-0"

[outputs]
section = ["HTML", "RSS", "print"]

[params]
copyright = "Ape Commerce"
github_repo = "https://github.com/ApeCommerce/apecommerce.github.io"
gcs_engine_id = "e5d47e28f9de542d3"
algolia_docsearch = false
offlineSearch = false

[params.ui]
navbar_translucent_over_cover_disable = true
sidebar_menu_compact = false
sidebar_search_disable = false
footer_about_disable = true

[[params.links.developer]]
name = "GitHub"
icon = "fab fa-github"
url = "https://github.com/ApeCommerce"
desc = "Development takes place here!"
